name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zig-version: [0.12.0, 0.14.0]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: ${{ matrix.zig-version }}

    - name: Build
      run: zig build

    - name: Test
      run: zig build test
